---
- include: 'tools.yml'
- include: 'git.yml'
- include: 'nodejs.yml'
- include: 'terraform.yml'
- include: 'python.yml'
- include: 'ruby.yml'
- include: 'docker.yml'
- include: 'go.yml'
- include: 'google-japanese-ime.yml'
- include: 'gradle.yml'
- include: 'intellj.yml'
- include: 'slack.yml'
- include: 'virtualbox.yml'
- include: 'iterm2.yml'
- include: 'chrome.yml'
- include: 'editor.yml'