---
- include: 'mac_default_write.yml'
- include: 'preconditions.yml'
- include: 'tools.yml'
- include: 'git.yml'
- include: 'nodejs.yml'
- include: 'terraform.yml'
- include: 'rust.yml'
- include: 'python.yml'
- include: 'ruby.yml'
- include: 'docker.yml'
- include: 'go.yml'
- include: 'java.yml'
- include: 'deno.yml'
- include: 'google-japanese-ime.yml'
- include: 'gradle.yml'
- include: 'intellj.yml'
- include: 'slack.yml'
- include: 'virtualbox.yml'
- include: 'iterm2.yml'
- include: 'chrome.yml'
- include: 'editor.yml'
- include: 'postman.yml'
- include: 'gui_archiver.yml'
- include: 'lua.yml'
- include: 'font.yml'
- include: 'app_cleaner.yml'
- include: 'nim.yml'
- include: 'alfred.yml'
- include: 'git-chglog.yml'
- include: 'gh.yml'
- include: 'dbeaver.yml'
- include: 'openvpn.yml'
- include: 'ffmpeg.yml'
