---
- name: 'Install Util tools'
  homebrew:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'awscli'
    - 'packer'
    - 'jq'
    - 'zsh'
    - 'tmux'
    - 'peco'
    - 'wget'
    - 'zplug'
    - 'reattach-to-user-namespace'
    - 'coreutils'
