---
- name: 'Install Util tools'
  homebrew:
    name: '{{ packages }}'
    state: 'present'
  vars:
    packages:
    - 'awscli'
    - 'awsebcli'
    - 'packer'
    - 'jq'
    - 'zsh'
    - 'tmux'
    - 'peco'
    - 'wget'
    - 'zplug'
    - 'reattach-to-user-namespace'
    - 'coreutils'
    - 'tree'
    - 'q'
    - 'htop'
    - 'editorconfig'
    - 'figlet'
    - 'nmap'
    - 'mtr'
    - 'automake'
    - 'autoconf'
    - 'openssl@1.1'
    - 'libyaml'
    - 'readline'
    - 'libxslt'
    - 'libtool'
    - 'unixodbc'
    - 'mycli'
    - 'the_silver_searcher'
    - 'tcptraceroute'
